### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#3]
Set up and populate a database for storing entities and their sources (possibly using CouchDB so that it has a native API querying mechanism, or using Neo4J for out-of-the-box graph visualization capabilities)

**Comment by Henni** [comment]
Summoning @MusicConnectionMachine/group-2 @MusicConnectionMachine/group-3 @MusicConnectionMachine/group-4 to this discussion.
I think we should get a decision for this soon!

I'd vote to go with Neo4j as it is a relationship oriented database which perfectly fits our use-case in my opinion.
I would love to see information like the [Bacon number](https://en.wikipedia.org/wiki/Six_Degrees_of_Kevin_Bacon) for classical music (maybe called "six degrees of Wolfgang Amadeus Mozart" :wink: ). Neo4j would be a natural fit for such queries as it is highly optimized for graph traversal.
BTW: [Mozart's Bacon number](https://www.google.de/search?q=bacon+number+Mozart) seems to be 4!

**Comment by metavaults** [comment]
As far as I'm concerned, Neo4j doesn't support JSON. However, the majority of our structured data is scraped in JSON format. If we go with Neo4j, we will have difficulties importing our data into the database.
My suggestion is MongoDB. NodeJS and MongoDB are 2 powers of web development right now. We could easily import our data and it's highly scalable. In addition to this, group 5 and 6 could easily implement Elasticsearch using MongoDB. Last but not least, MongoDB has a great documentation - if we run into problems, we can rely on it.

**Comment by Henni** [comment]
In my opinion MongoDB has real difficulties with modelling relationships. As we want to build a social graph in this project it would make sense to also use a graph database.
Regarding JSON: The data which will be imported into the database has to be parsed, so it shouldn't add a lot of complexity to store that in a different format than JSON. The data shouldn't be just copied into the database anyway.
ElasticSearch also integrates well with Neo4j and Neo4j should scale a lot better than MongoDB for this project because we heavily rely on relationship data.

**Comment by ansjin** [comment]
In my opinion also MongoDb doesn't work well for storing relationship data.  
You can check this link for details: 
http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/

**Comment by sacdallago** [comment]
Well, mongo **is not** a relational database system, thus per definition it won't manage relations well ( I mean, they are completely absent, there are no join operators, etc.). Neo4j is great for this use case, but then again: every database, to some extend, resembles a graph ( think about it :) ).

Nevertheless, I believe mongo can manage this type of data, better than neo4j due to the final `size` of the database. But still better would be using a good 'ol RDMS, and in this case I'd go for postgres.

Why?

1. It has relation capabilities
2. It can manage big amounts of data
3. It's ACID
4. You have an idea of the schema from the other data sources you are scraping


@vviro , anything to add?

**Comment by Henni** [comment]
~~@sacdallago a problem I see with RDMS is that it might be not flexible enough for us. Adding additional relationships might be easier in a NoSQL database.~~
EDIT: ok, nevermind... just talked with @ansjin about this :wink:

**Comment by sacdallago** [comment]
I understand that point, and it's a very valid one @TimHenkelmann . Still, weighing everything, I think that would be a better fit. If you are **strongly** against it, gimme some hardcore reason :)

**Comment by vviro** [comment]
I agree with @ansjin and @Henni, it seems that MongoDB is not a great fit for the project (http://developer.olery.com/blog/goodbye-mongodb-hello-postgresql/, https://www.linkedin.com/pulse/mongodb-frankenstein-monster-nosql-databases-john-de-goes). 

We should consider the amount of data we are going to be dealing with (especially coming from the unstructured sources). How many entities and relations are we expecting to extract and store in the database? Which queries are we going to run on the data? Will there be plenty of graph traversals, or counting/aggregations? Let's focus on discussing these requirements! For example, @Henni refers to the flexibility of working with different relationship types in the context of an RDBMS. Let's talk about this (though not in this post).

Neo4J seems to be perfect for the graph traversal use cases, whereas for aggregating data and generally handling large datasets Postgres is probably better. We still should do a more thorough requirements analysis, but at the moment I'd be more inclined to evaluate Postgres vs. Neo4j, and my best instant guess would be Postgres due to the data size, the performance requirements, feature set (btw, the JSON datatype is also supported) and the overall maturity of the project.

**Comment by vviro** [comment]
> Adding additional relationships might be easier in a NoSQL database.

@Henni can you expand upon this a bit? For example, which case could be problematic? Are you thinking of relationships between multiple entities (>2) that would be difficult to map to a relation of the type (relatishipTypeX, entityA, entityB), or maybe something else?

**Comment by ShilpaGhanashyamGore** [comment]
Also to consider is the proportion to which the relationships balloon. In the context of a social network ,the number of relationships that an entity is involved is way too many for a RDBMS to handle at the risk of not being the slowest element in the ecosystem . However , in the context of extracting relationships with confined scope as in Classical Music,  RDBMS (PostgreSQL ) will be able to handle as cyclic relationships and depth of Joins are not too much .

**Comment by pfent** [comment]
+1 for postgres.
Their [JSON](https://www.postgresql.org/docs/9.6/static/datatype-json.html) and NoSQL-like capabilities are really amazing in the latest versions

**Comment by kordianbruck** [comment]
You can also run both in parallel. Have the relations mapped in the proper DB that can easily give you what you require and then fetch the data from Mongo or Postgres. 

Another team is also setting up elastic in parallel to mongo. Using docker this should be little hassle to maintain.

**Comment by sacdallago** [comment]
@kordianbruck I can feel the pain of deploying this ahah Nevertheless, he is totally right. If you want to have flexibility at the level of the entities but strict relationship structure, mixing an RMSDB and a document-based DB _might_ be a good solution.

Nevertheless it will introduce some redundancy and if badly implemented can cause great pain. Also, it's only _eventually consistent_ because you cannot recover from transactions as a whole but only anatomically per-db (e.g.: you delete something from mongo, it works, then you delete something from Postgres, it fails --> Postgres will still have the data, mongo won't).

In this sense, using the JSON functionality of Postgres seems like a more appropriate choice!

**Comment by kordianbruck** [comment]
One can always say, that Postgres is the current view. Any other database might contain old/invalid data and needs to be verified before its send to the user. Yes its a huge pain, but might pay off if the features are so much better in other systems.

**Comment by sacdallago** [comment]
@kordianbruck that doesn't sound like a good solution to me. It impacts perfromance with filtering steps (maybe not huge impact, but scale it and you have a problem) and in the long run you might end up having huge inconsistencies and huge databases with a number of invalid data which is a pain to clean out :)

My final take is: Postgres with **as many fixed fields as possible put in columns** and a JSON field with a dump of extra, variable data. :) Who agrees?

**Comment by TimHenkelmann** [comment]
Closing this issue as PostgreSQL db was implemented quite some time ago!
